version: '3.7'

services:
  holder-api-service:
    image: ${CI_REGISTRY_IMAGE}/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
    restart: always
    ports:
      - "127.0.0.1:${SERVICE_PORT}:8000"
    env_file:
      - .env
    networks:
      - holder_net
    labels:
      app: holder-service

  
  redis:
    image: redis:alpine
    restart: always
    networks:
      - holder_net
    labels:
      app: holder-service

  celery:
    build: .
    command: [
      "celery",
      "-A",
      "tasks.worker",
      "worker",
      "-l",
      "info"
    ]
    restart: always
    env_file:
      - .env
    networks:
      - holder_net
    labels:
      app: holder-service
  

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - holder_net
    labels:
      app: holder-service


networks:
  holder_net:
    external: true
    name: holder-api-service_default
